name: 'FFmpeg'

output: '../lib/src/ffmpeg.g.dart'

headers:
  entry-points:
    - '../ffmpeg-headers/current/libpostproc/version.h'
    - '../ffmpeg-headers/current/libpostproc/version_major.h'
    - '../ffmpeg-headers/current/libpostproc/postprocess.h'
    - '../ffmpeg-headers/current/libavfilter/version.h'
    - '../ffmpeg-headers/current/libavfilter/buffersrc.h'
    - '../ffmpeg-headers/current/libavfilter/version_major.h'
    - '../ffmpeg-headers/current/libavfilter/buffersink.h'
    - '../ffmpeg-headers/current/libavfilter/avfilter.h'
    - '../ffmpeg-headers/current/libavutil/hwcontext.h'
    - '../ffmpeg-headers/current/libavutil/time.h'
    - '../ffmpeg-headers/current/libavutil/iamf.h'
    - '../ffmpeg-headers/current/libavutil/intfloat.h'
    - '../ffmpeg-headers/current/libavutil/error.h'
    - '../ffmpeg-headers/current/libavutil/detection_bbox.h'
    - '../ffmpeg-headers/current/libavutil/ambient_viewing_environment.h'
    - '../ffmpeg-headers/current/libavutil/fifo.h'
    - '../ffmpeg-headers/current/libavutil/blowfish.h'
    - '../ffmpeg-headers/current/libavutil/replaygain.h'
    - '../ffmpeg-headers/current/libavutil/version.h'
    - '../ffmpeg-headers/current/libavutil/murmur3.h'
    - '../ffmpeg-headers/current/libavutil/stereo3d.h'
    - '../ffmpeg-headers/current/libavutil/samplefmt.h'
    - '../ffmpeg-headers/current/libavutil/pixdesc.h'
    - '../ffmpeg-headers/current/libavutil/base64.h'
    - '../ffmpeg-headers/current/libavutil/rational.h'
    - '../ffmpeg-headers/current/libavutil/sha.h'
    - '../ffmpeg-headers/current/libavutil/motion_vector.h'
    - '../ffmpeg-headers/current/libavutil/uuid.h'
    - '../ffmpeg-headers/current/libavutil/avconfig.h'
    - '../ffmpeg-headers/current/libavutil/lfg.h'
    - '../ffmpeg-headers/current/libavutil/avutil.h'
    - '../ffmpeg-headers/current/libavutil/xtea.h'
    - '../ffmpeg-headers/current/libavutil/crc.h'
    - '../ffmpeg-headers/current/libavutil/frame.h'
    - '../ffmpeg-headers/current/libavutil/file.h'
    - '../ffmpeg-headers/current/libavutil/md5.h'
    - '../ffmpeg-headers/current/libavutil/cast5.h'
    - '../ffmpeg-headers/current/libavutil/spherical.h'
    - '../ffmpeg-headers/current/libavutil/ffversion.h'
    - '../ffmpeg-headers/current/libavutil/audio_fifo.h'
    - '../ffmpeg-headers/current/libavutil/tree.h'
    - '../ffmpeg-headers/current/libavutil/threadmessage.h'
    - '../ffmpeg-headers/current/libavutil/attributes.h'
    - '../ffmpeg-headers/current/libavutil/hdr_dynamic_vivid_metadata.h'
    - '../ffmpeg-headers/current/libavutil/adler32.h'
    - '../ffmpeg-headers/current/libavutil/timecode.h'
    - '../ffmpeg-headers/current/libavutil/dovi_meta.h'
    - '../ffmpeg-headers/current/libavutil/tx.h'
    - '../ffmpeg-headers/current/libavutil/sha512.h'
    - '../ffmpeg-headers/current/libavutil/display.h'
    - '../ffmpeg-headers/current/libavutil/buffer.h'
    - '../ffmpeg-headers/current/libavutil/camellia.h'
    - '../ffmpeg-headers/current/libavutil/csp.h'
    - '../ffmpeg-headers/current/libavutil/video_hint.h'
    - '../ffmpeg-headers/current/libavutil/pixelutils.h'
    - '../ffmpeg-headers/current/libavutil/common.h'
    - '../ffmpeg-headers/current/libavutil/hmac.h'
    - '../ffmpeg-headers/current/libavutil/eval.h'
    - '../ffmpeg-headers/current/libavutil/executor.h'
    - '../ffmpeg-headers/current/libavutil/dict.h'
    - '../ffmpeg-headers/current/libavutil/random_seed.h'
    - '../ffmpeg-headers/current/libavutil/opt.h'
    - '../ffmpeg-headers/current/libavutil/mastering_display_metadata.h'
    - '../ffmpeg-headers/current/libavutil/log.h'
    - '../ffmpeg-headers/current/libavutil/aes.h'
    - '../ffmpeg-headers/current/libavutil/macros.h'
    - '../ffmpeg-headers/current/libavutil/bswap.h'
    - '../ffmpeg-headers/current/libavutil/rc4.h'
    - '../ffmpeg-headers/current/libavutil/tea.h'
    - '../ffmpeg-headers/current/libavutil/cpu.h'
    - '../ffmpeg-headers/current/libavutil/lzo.h'
    - '../ffmpeg-headers/current/libavutil/des.h'
    - '../ffmpeg-headers/current/libavutil/channel_layout.h'
    - '../ffmpeg-headers/current/libavutil/encryption_info.h'
    - '../ffmpeg-headers/current/libavutil/twofish.h'
    - '../ffmpeg-headers/current/libavutil/imgutils.h'
    - '../ffmpeg-headers/current/libavutil/video_enc_params.h'
    - '../ffmpeg-headers/current/libavutil/mem.h'
    - '../ffmpeg-headers/current/libavutil/parseutils.h'
    - '../ffmpeg-headers/current/libavutil/ripemd.h'
    - '../ffmpeg-headers/current/libavutil/bprint.h'
    - '../ffmpeg-headers/current/libavutil/hdr_dynamic_metadata.h'
    - '../ffmpeg-headers/current/libavutil/pixfmt.h'
    - '../ffmpeg-headers/current/libavutil/aes_ctr.h'
    - '../ffmpeg-headers/current/libavutil/timestamp.h'
    - '../ffmpeg-headers/current/libavutil/downmix_info.h'
    - '../ffmpeg-headers/current/libavutil/avassert.h'
    - '../ffmpeg-headers/current/libavutil/hash.h'
    - '../ffmpeg-headers/current/libavutil/mathematics.h'
    - '../ffmpeg-headers/current/libavutil/intreadwrite.h'
    - '../ffmpeg-headers/current/libavutil/film_grain_params.h'
    - '../ffmpeg-headers/current/libavutil/avstring.h'
    - '../ffmpeg-headers/current/libavdevice/version.h'
    - '../ffmpeg-headers/current/libavdevice/avdevice.h'
    - '../ffmpeg-headers/current/libavdevice/version_major.h'
    - '../ffmpeg-headers/current/libavformat/version.h'
    - '../ffmpeg-headers/current/libavformat/version_major.h'
    - '../ffmpeg-headers/current/libavformat/avio.h'
    - '../ffmpeg-headers/current/libavformat/avformat.h'
    - '../ffmpeg-headers/current/libswscale/version.h'
    - '../ffmpeg-headers/current/libswscale/swscale.h'
    - '../ffmpeg-headers/current/libswscale/version_major.h'
    - '../ffmpeg-headers/current/libavcodec/adts_parser.h'
    - '../ffmpeg-headers/current/libavcodec/avcodec.h'
    - '../ffmpeg-headers/current/libavcodec/defs.h'
    - '../ffmpeg-headers/current/libavcodec/version.h'
    - '../ffmpeg-headers/current/libavcodec/codec_par.h'
    - '../ffmpeg-headers/current/libavcodec/codec_desc.h'
    - '../ffmpeg-headers/current/libavcodec/mediacodec.h'
    - '../ffmpeg-headers/current/libavcodec/avfft.h'
    - '../ffmpeg-headers/current/libavcodec/codec.h'
    - '../ffmpeg-headers/current/libavcodec/jni.h'
    - '../ffmpeg-headers/current/libavcodec/packet.h'
    - '../ffmpeg-headers/current/libavcodec/version_major.h'
    - '../ffmpeg-headers/current/libavcodec/bsf.h'
    - '../ffmpeg-headers/current/libavcodec/codec_id.h'
    - '../ffmpeg-headers/current/libavcodec/dirac.h'
    - '../ffmpeg-headers/current/libavcodec/avdct.h'
    - '../ffmpeg-headers/current/libavcodec/ac3_parser.h'
    - '../ffmpeg-headers/current/libavcodec/vorbis_parser.h'
    - '../ffmpeg-headers/current/libavcodec/dv_profile.h'
    - '../ffmpeg-headers/current/libswresample/version.h'
    - '../ffmpeg-headers/current/libswresample/version_major.h'
    - '../ffmpeg-headers/current/libswresample/swresample.h'

compiler-opts:
  - '-Iffmpeg-headers/current'

llvm-path:
  - '/Library/Developer/CommandLineTools/usr/lib/'

preamble: |
  // ignore_for_file: type=lint, doc_directive_unknown, unused_field, unused_element

silence-enum-warning: true
