name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  ffipeg:
  ffi: ^2.1.3

dev_dependencies:
  build_runner: ^2.4.13
  ffipeg_builder:
  lints: ^5.0.0
