name: ffipeg_dart

repository: https://github.com/dra11y/ffipeg-dart

packages:
  - packages/ffipeg
  - packages/ffipeg_builder
  - packages/ffipeg_muxer

scripts:
  fix:
    exec: dart fix --apply
  watch:
    exec: dart run build_runner watch -d
    packageFilters:
      scope: ffipeg_muxer

ide:
  intellij:
    enabled: false

command:
  publish:
    hooks:
      pre: |
        melos exec --scope=ffipeg_muxer "dart run build_runner build"
        cat packages/ffipeg_muxer/lib/src/{muxer,muxer_result}.dart | tee packages/{ffipeg,ffipeg_builder}/example/main.dart
        find . -name .DS_Store | xargs rm
  version:
    hooks:
      preCommit: melos exec --scope=ffipeg_muxer "dart run build_runner build"
