builders:
  ffmpeg_builder:
    import: "package:ffipeg_builder/ffipeg_builder.dart"
    builder_factories: ["ffmpegBuilderFactory"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: dependents
    build_to: source
