name: ffipeg_builder
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

dependencies:
  analyzer: ^6.8.0 # > 6.9 requires macros
  build: ^2.4.1
  ffi: ^2.1.3
  ffigen: ^14.0.1
  ffipeg:
    path: ../ffipeg
  glob: ^2.1.2
  lints: ^5.0.0
  logging: ^1.2.0
  path: ^1.9.0
  source_gen: ^1.5.0
  yaml: ^3.1.2

dev_dependencies:
  test: ^1.25.8
