name: ffipeg_muxer
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

dependencies:
  args: ^2.5.0
  ffi: ^2.1.3
  ffipeg:
  logging: ^1.2.0
  path: ^1.9.0

dev_dependencies:
  build_runner: ^2.4.13
  ffipeg_builder:
  lints: ^5.0.0
  test: ^1.25.8
