name: ffipeg_muxer
description: CLI and API to use FFmpeg FFI to mux separate audio and video files into a single output file.
version: 0.1.1+2
repository: https://github.com/dra11y/ffipeg-dart

environment:
  sdk: ^3.5.3

dependencies:
  args: ^2.5.0
  ffi: ^2.1.3
  ffipeg: ^0.1.1
  logging: ^1.2.0
  path: ^1.9.0

dev_dependencies:
  build_runner: ^2.4.13
  build_version: ^2.1.1
  ffipeg_builder: ^0.1.1
  lints: ^5.0.0
  test: ^1.25.8
