name: ffipeg
description: Dart FFI bindings generator for FFmpeg
version: 0.1.1
repository: https://github.com/dra11y/ffipeg-dart

environment:
  sdk: ^3.5.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
