builders:
  ffmpeg_config_builder:
    import: "package:ffipeg_builder/ffipeg_builder.dart"
    builder_factories: ["ffmpegConfigBuilderFactory"]
    build_extensions: {".dart": [".ffipeg.json"]}
    runs_before: ["ffmpeg_ffigen_builder"]
    auto_apply: dependents
    build_to: cache

  ffmpeg_ffigen_builder:
    import: "package:ffipeg_builder/ffipeg_builder.dart"
    builder_factories: ["ffmpegFfiGenBuilderFactory"]
    required_inputs: [".ffipeg.json"]
    build_extensions: {".ffipeg.json": [".ffipeg.dart"]}
    auto_apply: dependents
    build_to: source
