name: ffipeg_builder
description: Builder dev dependency for ffipeg -- Generate Dart FFI bindings to FFmpeg with a simple library annotation.
version: 0.1.1+4
repository: https://github.com/dra11y/ffipeg-dart

environment:
  sdk: ^3.5.3

dependencies:
  # analyzer: ^6.7.0 # 6.8 req collection 1.19; > 6.9 req main ch./macros
  analyzer: ^6.6.0
  build: ^2.4.1
  ffi: ^2.1.3
  ffigen: ^14.0.1
  ffipeg: ^0.1.1+4
  glob: ^2.1.2
  lints: ^5.0.0
  logging: ^1.2.0
  path: ^1.9.0
  source_gen: ^1.5.0
  yaml: ^3.1.2

dev_dependencies:
  test: ^1.25.8
